//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurDoc
    {
        public int Id_CurDoc { get; set; }
        public Nullable<int> Id_Curso { get; set; }
        public Nullable<int> Id_Docente { get; set; }
    
        public virtual Cursos Cursos { get; set; }
        public virtual Docentes Docentes { get; set; }
    }
}
