//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ColegioEntities : DbContext
    {
        public ColegioEntities()
            : base("name=ColegioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlumCur> AlumCur { get; set; }
        public virtual DbSet<Alumnos> Alumnos { get; set; }
        public virtual DbSet<CurDoc> CurDoc { get; set; }
        public virtual DbSet<Cursos> Cursos { get; set; }
        public virtual DbSet<Docentes> Docentes { get; set; }
        public virtual DbSet<MatCur> MatCur { get; set; }
        public virtual DbSet<Materias> Materias { get; set; }
        public virtual DbSet<Notas> Notas { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
